### ISSUE TITLE
running templ generate after pull breaks build

### ISSUE THREAD

**Issue by DenizChildir** [emarifer/gofiber-templ-htmx#1]
for some reason, you can build and run and it works correctly. if you run templ generate, it just breaks.

PS C:\Users\u\Desktop\gofiber-templ-htmx> go build
PS C:\Users\u\Desktop\gofiber-templ-htmx> templ generate
(!) templ version check: generator v0.2.646 is newer than templ version v0.2.476 found in go.mod file, consider running `go get -u github.com/a-h/templ` to upgrade
(✓) Complete [ updates=9 duration=9.774ms ]
PS C:\Users\u\Desktop\gofiber-templ-htmx> go build
# github.com/emarifer/gofiber-templ-htmx/views/partials
views\partials\flashmessages.partial_templ.go:40:52: undefined: templ.JoinStringErrs
views\partials\flashmessages.partial_templ.go:42:18: undefined: templ.Error
views\partials\flashmessages.partial_templ.go:68:52: undefined: templ.JoinStringErrs
views\partials\flashmessages.partial_templ.go:70:18: undefined: templ.Error
views\partials\navbar.partial_templ.go:36:52: undefined: templ.JoinStringErrs
views\partials\navbar.partial_templ.go:38:18: undefined: templ.Error

**Comment by emarifer** [comment]
I think it is related to the fact that you are on Windows (it works correctly on Linux). That seems to happen with [templ v0.2.476](https://stackoverflow.com/questions/77697430/go-undefined-functions-in-templ-object). Try updating the **a-h.templ** package and compiler to v0.2.648.

**Comment by emarifer** [comment]
@DenizChildir
