### ISSUE TITLE
Errors on go mod tidy

### ISSUE THREAD

**Issue by rafidude** [emarifer/gofiber-templ-htmx#2]
$ go install github.com/a-h/templ/cmd/templ@latest
go: downloading github.com/a-h/templ v0.2.747
go: downloading github.com/a-h/protocol v0.0.0-20240704131721-1e461c188041

$ go mod tidy
go: downloading github.com/gofiber/fiber/v2 v2.51.0
go: downloading github.com/mattn/go-sqlite3 v1.14.18
go: downloading golang.org/x/crypto v0.24.0
go: downloading github.com/sujit-baniya/flash v0.1.8
go: downloading github.com/google/uuid v1.4.0
go: downloading github.com/valyala/fasthttp v1.55.0
go: downloading github.com/klauspost/compress v1.17.9
go: finding module for package github.com/emarifer/gofiber-templ-htmx/views/todo_views
go: finding module for package github.com/emarifer/gofiber-templ-htmx/views
go: finding module for package github.com/emarifer/gofiber-templ-htmx/views/auth_views
go: github.com/emarifer/gofiber-templ-htmx/handlers imports
	github.com/emarifer/gofiber-templ-htmx/views: no matching versions for query "latest"
go: github.com/emarifer/gofiber-templ-htmx/handlers imports
	github.com/emarifer/gofiber-templ-htmx/views/auth_views: no matching versions for query "latest"
go: github.com/emarifer/gofiber-templ-htmx/handlers imports
	github.com/emarifer/gofiber-templ-htmx/views/todo_views: no matching versions for query "latest"

**Comment by emarifer** [comment]
Hi, **rafidude**

You missed the template compilation step. As explained at the end of the README, with the `templ` binary installed, you must run this:

```
$ templ generate # The `templ generate --watch` command will watch the project folder to regenerate them every time we make a change to its code.
```

Once that is done you can run `go mod tidy`.

If you have the [air](https://github.com/air-verse/air) tool installed, which also allows hot reloading, the template compilation step and dependency downloading is automatic, as the `.air.toml` file has been configured for that purpose..
